### ISSUE TITLE
Doesn't work on Google Sites

### ISSUE THREAD

**Issue by nchantal** [Foxy/chrome-type-ahead#10]
I make a Google Sites homepage with all the links I commonly visit for work. chrome-type-ahead used to work on this page, but it seems to have broken recently.

**Comment by brettflorio** [comment]
@nchantal Can you provide a URL to see this issue?

**Comment by nchantal** [comment]
No, I don’t use the site anymore

**Comment by brettflorio** [comment]
@nchantal Thanks for the response. We'll close for now then.
