### ISSUE TITLE
contenteditable

### ISSUE THREAD

**Issue by gdandersson** [Foxy/chrome-type-ahead#12]
When an element that isn't an input element BUT has contenteditable, type-ahead-find receives the input when that element should receive it.

Discovered when trying to implement https://yaireo.github.io/tagify/ on a site

**Comment by brettflorio** [comment]
@gdandersson Submitted a new version for review. Not sure how long it'll take, but it should go live as soon as it's reviewed and approved. Thanks for submitting the bug!

**Comment by gdandersson** [comment]
Perfect, thank you!
