### ISSUE TITLE
Unable to find words within embeded content

### ISSUE THREAD

**Issue by Tarrnation** [Foxy/chrome-type-ahead#2]
This extension does not appear to find anything that is within embeded content.

For example, try using the extension to find the word "mage" on the following page: http://ggoatgaming.com/tierlist/

"mage" does not appear on the page itself, but within the embedded spreadsheet, it appears 6 times.

**Comment by brettflorio** [comment]
Closing, as that URL isn't live anymore to test, but we can reopen if another example is provided.
