### ISSUE TITLE
Wonky scrolling

### ISSUE THREAD

**Issue by linesarefuzzy** [Foxy/chrome-type-ahead#6]
On [this page](https://www.irs.gov/irm/part7/irm_07-025-003), using the extension to search for "unincorporated" on my Chrome on Mac causes the page to scroll off to the left of the window and I can't scroll it back. The only way I am able to get it back is to click the "English" link at the top. Chrome's built-in find doesn't have this problem. 

P.S. Thanks for making this extension!

**Comment by brettflorio** [comment]
@linesarefuzzy That link is broken. Closing this issue for now but if you see it again, please comment with a link and we can reopen. Thanks!
