### ISSUE TITLE
contentdeditable doesn't disable search

### ISSUE THREAD

**Issue by Gregormo** [Foxy/chrome-type-ahead#7]
If I type in an HTML element with the `contentdeditable` attribute set, type-ahead-find ist triggered and the browser searches for the text instead of editing the content of the HTML element. If `contentdeditable` is set, type-ahead-find should treat the element like an `input` or `textarea` instead. HTML snippet looks like this, for example: `<h1 contenteditable>foo</h1>`

The code seems to check for the contentdeditable attribute already, so I don't get why it doesn't work. I don't really know Javascript, so sadly I'm not able to contribute a patch. 

Thanks for this reat plugin!

**Comment by brettflorio** [comment]
@Gregormo The [`contenteditable` example on the Mozilla page](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) seems to work properly. Do you have another example where it's not working?

**Comment by brettflorio** [comment]
Closing. If we get another example, we can reopen.
